export const GET_CUSTOM_ANALYTICS = "GET_CUSTOM_ANALYTICS";
// export const GET_SEARCH_USER="GET_SEARCH_USER";
export const  SEARCH_USER="SEARCH_USER"


export const POST_BOOKING_CUSTOM_ANALYTICS = 'POST_BOOKING_CUSTOM_ANALYTICS';
export const POST_CANCEL_BOOKING_CUSTOM_ANALYTICS="POST_CANCEL_BOOKING_CUSTOM_ANALYTICS"