export const SEND_TOKEN_LIST = "SEND_TOKEN_LIST";
export const RECEIVED_USD_LIST = "RECEIVED_USD_LIST";
export const PAYMENT_TOKEN_HISTORY_SEARCH = "PAYMENT_TOKEN_HISTORY_SEARCH";
export const SEND_TOKEN_FILTER = "SEND_TOKEN_FILTER";
