export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_AUTH_LOADING = "SET_AUTH_LOADING";
export const REMOVE_AUTH_LOADING = "REMOVE_AUTH_LOADING";
export const LOGOUT_USER = "LOGOUT_USER";
export const GET_ALL_STATS = "GET_ALL_STATS";
export const GET_ALL_PERMISSIONS = "GET_ALL_PERMISSIONS";
export const PERMISSIONS = "PERMISSIONS";
