export const GET_CAB_BOOKING_DETAIL = "GET_CAB_BOOKING_DETAIL";
export const GET_CAB_BOOKING = "GET_CAB_BOOKING";
export const GET_CAB_PAYMENTS_LIST = "GET_PAYMENTS_LIST";
export const GET_CAB_TIP_LIST = "GET_TIP_LIST";