export const GET_RATTING_LIST = "GET_RATTING_LIST";
export const GET_RATTING_BY_ID = "GET_RATTING_BY_ID";
export const UPDATE_RATTING = "UPDATE_RATTING";
export const DELETE_RATTING = "DELETE_RATTING";
