export const GET_ALL_ADMIN_NOTIFICATION = "GET_ALL_ADMIN_NOTIFICATION";
export const CREATE_ADMIN_NOTIFICATION = 'CREATE_ADMIN_NOTIFICATION'
export const GET_ALL_ADMIN_NOTIFICATION_COUNT = 'GET_ALL_ADMIN_NOTIFICATION_COUNT'