[
  {
    id: 1,
    name: "Can add log entry",
    content_type_id: 1,
    codename: "add_logentry",
  },
  {
    id: 2,
    name: "Can change log entry",
    content_type_id: 1,
    codename: "change_logentry",
  },
  {
    id: 3,
    name: "Can delete log entry",
    content_type_id: 1,
    codename: "delete_logentry",
  },
  {
    id: 4,
    name: "Can view log entry",
    content_type_id: 1,
    codename: "view_logentry",
  },
  {
    id: 9,
    name: "Can add group",
    content_type_id: 3,
    codename: "add_group",
  },
  {
    id: 10,
    name: "Can change group",
    content_type_id: 3,
    codename: "change_group",
  },
  {
    id: 11,
    name: "Can delete group",
    content_type_id: 3,
    codename: "delete_group",
  },
  {
    id: 12,
    name: "Can view group",
    content_type_id: 3,
    codename: "view_group",
  },
  {
    id: 5,
    name: "Can add permission",
    content_type_id: 2,
    codename: "add_permission",
  },
  {
    id: 6,
    name: "Can change permission",
    content_type_id: 2,
    codename: "change_permission",
  },
  {
    id: 7,
    name: "Can delete permission",
    content_type_id: 2,
    codename: "delete_permission",
  },
  {
    id: 8,
    name: "Can view permission",
    content_type_id: 2,
    codename: "view_permission",
  },
  {
    id: 13,
    name: "Can add user",
    content_type_id: 4,
    codename: "add_user",
  },
  {
    id: 14,
    name: "Can change user",
    content_type_id: 4,
    codename: "change_user",
  },
  {
    id: 15,
    name: "Can delete user",
    content_type_id: 4,
    codename: "delete_user",
  },
  {
    id: 16,
    name: "Can view user",
    content_type_id: 4,
    codename: "view_user",
  },
  {
    id: 57,
    name: "Can add admin convenience fee",
    content_type_id: 15,
    codename: "add_adminconveniencefee",
  },
  {
    id: 58,
    name: "Can change admin convenience fee",
    content_type_id: 15,
    codename: "change_adminconveniencefee",
  },
  {
    id: 59,
    name: "Can delete admin convenience fee",
    content_type_id: 15,
    codename: "delete_adminconveniencefee",
  },
  {
    id: 60,
    name: "Can view admin convenience fee",
    content_type_id: 15,
    codename: "view_adminconveniencefee",
  },
  {
    id: 105,
    name: "Can add admin transaction list",
    content_type_id: 27,
    codename: "add_admintransactionlist",
  },
  {
    id: 106,
    name: "Can change admin transaction list",
    content_type_id: 27,
    codename: "change_admintransactionlist",
  },
  {
    id: 107,
    name: "Can delete admin transaction list",
    content_type_id: 27,
    codename: "delete_admintransactionlist",
  },
  {
    id: 108,
    name: "Can view admin transaction list",
    content_type_id: 27,
    codename: "view_admintransactionlist",
  },
  {
    id: 61,
    name: "Can add answer",
    content_type_id: 16,
    codename: "add_answer",
  },
  {
    id: 62,
    name: "Can change answer",
    content_type_id: 16,
    codename: "change_answer",
  },
  {
    id: 63,
    name: "Can delete answer",
    content_type_id: 16,
    codename: "delete_answer",
  },
  {
    id: 64,
    name: "Can view answer",
    content_type_id: 16,
    codename: "view_answer",
  },
  {
    id: 101,
    name: "Can add bids",
    content_type_id: 26,
    codename: "add_bids",
  },
  {
    id: 102,
    name: "Can change bids",
    content_type_id: 26,
    codename: "change_bids",
  },
  {
    id: 103,
    name: "Can delete bids",
    content_type_id: 26,
    codename: "delete_bids",
  },
  {
    id: 104,
    name: "Can view bids",
    content_type_id: 26,
    codename: "view_bids",
  },
  {
    id: 65,
    name: "Can add booking",
    content_type_id: 17,
    codename: "add_booking",
  },
  {
    id: 66,
    name: "Can change booking",
    content_type_id: 17,
    codename: "change_booking",
  },
  {
    id: 67,
    name: "Can delete booking",
    content_type_id: 17,
    codename: "delete_booking",
  },
  {
    id: 68,
    name: "Can view booking",
    content_type_id: 17,
    codename: "view_booking",
  },
  {
    id: 97,
    name: "Can add dispute",
    content_type_id: 25,
    codename: "add_dispute",
  },
  {
    id: 98,
    name: "Can change dispute",
    content_type_id: 25,
    codename: "change_dispute",
  },
  {
    id: 99,
    name: "Can delete dispute",
    content_type_id: 25,
    codename: "delete_dispute",
  },
  {
    id: 100,
    name: "Can view dispute",
    content_type_id: 25,
    codename: "view_dispute",
  },
  {
    id: 233,
    name: "Can add dispute files",
    content_type_id: 59,
    codename: "add_disputefiles",
  },
  {
    id: 234,
    name: "Can change dispute files",
    content_type_id: 59,
    codename: "change_disputefiles",
  },
  {
    id: 235,
    name: "Can delete dispute files",
    content_type_id: 59,
    codename: "delete_disputefiles",
  },
  {
    id: 236,
    name: "Can view dispute files",
    content_type_id: 59,
    codename: "view_disputefiles",
  },
  {
    id: 93,
    name: "Can add job files",
    content_type_id: 24,
    codename: "add_jobfiles",
  },
  {
    id: 94,
    name: "Can change job files",
    content_type_id: 24,
    codename: "change_jobfiles",
  },
  {
    id: 95,
    name: "Can delete job files",
    content_type_id: 24,
    codename: "delete_jobfiles",
  },
  {
    id: 96,
    name: "Can view job files",
    content_type_id: 24,
    codename: "view_jobfiles",
  },
  {
    id: 89,
    name: "Can add jobs",
    content_type_id: 23,
    codename: "add_jobs",
  },
  {
    id: 90,
    name: "Can change jobs",
    content_type_id: 23,
    codename: "change_jobs",
  },
  {
    id: 91,
    name: "Can delete jobs",
    content_type_id: 23,
    codename: "delete_jobs",
  },
  {
    id: 92,
    name: "Can view jobs",
    content_type_id: 23,
    codename: "view_jobs",
  },
  {
    id: 85,
    name: "Can add rating",
    content_type_id: 22,
    codename: "add_rating",
  },
  {
    id: 86,
    name: "Can change rating",
    content_type_id: 22,
    codename: "change_rating",
  },
  {
    id: 87,
    name: "Can delete rating",
    content_type_id: 22,
    codename: "delete_rating",
  },
  {
    id: 88,
    name: "Can view rating",
    content_type_id: 22,
    codename: "view_rating",
  },
  {
    id: 273,
    name: "Can add refund mln",
    content_type_id: 69,
    codename: "add_refundmln",
  },
  {
    id: 274,
    name: "Can change refund mln",
    content_type_id: 69,
    codename: "change_refundmln",
  },
  {
    id: 275,
    name: "Can delete refund mln",
    content_type_id: 69,
    codename: "delete_refundmln",
  },
  {
    id: 276,
    name: "Can view refund mln",
    content_type_id: 69,
    codename: "view_refundmln",
  },
  {
    id: 81,
    name: "Can add sp add price",
    content_type_id: 21,
    codename: "add_spaddprice",
  },
  {
    id: 82,
    name: "Can change sp add price",
    content_type_id: 21,
    codename: "change_spaddprice",
  },
  {
    id: 83,
    name: "Can delete sp add price",
    content_type_id: 21,
    codename: "delete_spaddprice",
  },
  {
    id: 84,
    name: "Can view sp add price",
    content_type_id: 21,
    codename: "view_spaddprice",
  },
  {
    id: 77,
    name: "Can add sp service images",
    content_type_id: 20,
    codename: "add_spserviceimages",
  },
  {
    id: 78,
    name: "Can change sp service images",
    content_type_id: 20,
    codename: "change_spserviceimages",
  },
  {
    id: 79,
    name: "Can delete sp service images",
    content_type_id: 20,
    codename: "delete_spserviceimages",
  },
  {
    id: 80,
    name: "Can view sp service images",
    content_type_id: 20,
    codename: "view_spserviceimages",
  },
  {
    id: 73,
    name: "Can add spservices",
    content_type_id: 19,
    codename: "add_spservices",
  },
  {
    id: 74,
    name: "Can change spservices",
    content_type_id: 19,
    codename: "change_spservices",
  },
  {
    id: 75,
    name: "Can delete spservices",
    content_type_id: 19,
    codename: "delete_spservices",
  },
  {
    id: 76,
    name: "Can view spservices",
    content_type_id: 19,
    codename: "view_spservices",
  },
  {
    id: 69,
    name: "Can add tip",
    content_type_id: 18,
    codename: "add_tip",
  },
  {
    id: 70,
    name: "Can change tip",
    content_type_id: 18,
    codename: "change_tip",
  },
  {
    id: 71,
    name: "Can delete tip",
    content_type_id: 18,
    codename: "delete_tip",
  },
  {
    id: 72,
    name: "Can view tip",
    content_type_id: 18,
    codename: "view_tip",
  },
  {
    id: 213,
    name: "Can add category kyc",
    content_type_id: 54,
    codename: "add_categorykyc",
  },
  {
    id: 214,
    name: "Can change category kyc",
    content_type_id: 54,
    codename: "change_categorykyc",
  },
  {
    id: 215,
    name: "Can delete category kyc",
    content_type_id: 54,
    codename: "delete_categorykyc",
  },
  {
    id: 216,
    name: "Can view category kyc",
    content_type_id: 54,
    codename: "view_categorykyc",
  },
  {
    id: 221,
    name: "Can add category kyc answer",
    content_type_id: 56,
    codename: "add_categorykycanswer",
  },
  {
    id: 222,
    name: "Can change category kyc answer",
    content_type_id: 56,
    codename: "change_categorykycanswer",
  },
  {
    id: 223,
    name: "Can delete category kyc answer",
    content_type_id: 56,
    codename: "delete_categorykycanswer",
  },
  {
    id: 224,
    name: "Can view category kyc answer",
    content_type_id: 56,
    codename: "view_categorykycanswer",
  },
  {
    id: 225,
    name: "Can add category kyc answer file",
    content_type_id: 57,
    codename: "add_categorykycanswerfile",
  },
  {
    id: 226,
    name: "Can change category kyc answer file",
    content_type_id: 57,
    codename: "change_categorykycanswerfile",
  },
  {
    id: 227,
    name: "Can delete category kyc answer file",
    content_type_id: 57,
    codename: "delete_categorykycanswerfile",
  },
  {
    id: 228,
    name: "Can view category kyc answer file",
    content_type_id: 57,
    codename: "view_categorykycanswerfile",
  },
  {
    id: 217,
    name: "Can add category specific kyc",
    content_type_id: 55,
    codename: "add_categoryspecifickyc",
  },
  {
    id: 218,
    name: "Can change category specific kyc",
    content_type_id: 55,
    codename: "change_categoryspecifickyc",
  },
  {
    id: 219,
    name: "Can delete category specific kyc",
    content_type_id: 55,
    codename: "delete_categoryspecifickyc",
  },
  {
    id: 220,
    name: "Can view category specific kyc",
    content_type_id: 55,
    codename: "view_categoryspecifickyc",
  },
  {
    id: 41,
    name: "Can add category",
    content_type_id: 11,
    codename: "add_category",
  },
  {
    id: 42,
    name: "Can change category",
    content_type_id: 11,
    codename: "change_category",
  },
  {
    id: 43,
    name: "Can delete category",
    content_type_id: 11,
    codename: "delete_category",
  },
  {
    id: 44,
    name: "Can view category",
    content_type_id: 11,
    codename: "view_category",
  },
  {
    id: 45,
    name: "Can add category questions",
    content_type_id: 12,
    codename: "add_categoryquestions",
  },
  {
    id: 46,
    name: "Can change category questions",
    content_type_id: 12,
    codename: "change_categoryquestions",
  },
  {
    id: 47,
    name: "Can delete category questions",
    content_type_id: 12,
    codename: "delete_categoryquestions",
  },
  {
    id: 48,
    name: "Can view category questions",
    content_type_id: 12,
    codename: "view_categoryquestions",
  },
  {
    id: 17,
    name: "Can add content type",
    content_type_id: 5,
    codename: "add_contenttype",
  },
  {
    id: 18,
    name: "Can change content type",
    content_type_id: 5,
    codename: "change_contenttype",
  },
  {
    id: 19,
    name: "Can delete content type",
    content_type_id: 5,
    codename: "delete_contenttype",
  },
  {
    id: 20,
    name: "Can view content type",
    content_type_id: 5,
    codename: "view_contenttype",
  },
  {
    id: 269,
    name: "Can add admin dispute comments",
    content_type_id: 68,
    codename: "add_admindisputecomments",
  },
  {
    id: 270,
    name: "Can change admin dispute comments",
    content_type_id: 68,
    codename: "change_admindisputecomments",
  },
  {
    id: 271,
    name: "Can delete admin dispute comments",
    content_type_id: 68,
    codename: "delete_admindisputecomments",
  },
  {
    id: 272,
    name: "Can view admin dispute comments",
    content_type_id: 68,
    codename: "view_admindisputecomments",
  },
  {
    id: 129,
    name: "Can add document",
    content_type_id: 33,
    codename: "add_document",
  },
  {
    id: 130,
    name: "Can change document",
    content_type_id: 33,
    codename: "change_document",
  },
  {
    id: 131,
    name: "Can delete document",
    content_type_id: 33,
    codename: "delete_document",
  },
  {
    id: 132,
    name: "Can view document",
    content_type_id: 33,
    codename: "view_document",
  },
  {
    id: 133,
    name: "Can add kyc answer",
    content_type_id: 34,
    codename: "add_kycanswer",
  },
  {
    id: 134,
    name: "Can change kyc answer",
    content_type_id: 34,
    codename: "change_kycanswer",
  },
  {
    id: 135,
    name: "Can delete kyc answer",
    content_type_id: 34,
    codename: "delete_kycanswer",
  },
  {
    id: 136,
    name: "Can view kyc answer",
    content_type_id: 34,
    codename: "view_kycanswer",
  },
  {
    id: 117,
    name: "Can add faqs",
    content_type_id: 30,
    codename: "add_faqs",
  },
  {
    id: 118,
    name: "Can change faqs",
    content_type_id: 30,
    codename: "change_faqs",
  },
  {
    id: 119,
    name: "Can delete faqs",
    content_type_id: 30,
    codename: "delete_faqs",
  },
  {
    id: 120,
    name: "Can view faqs",
    content_type_id: 30,
    codename: "view_faqs",
  },
  {
    id: 253,
    name: "Can add inventory",
    content_type_id: 64,
    codename: "add_inventory",
  },
  {
    id: 254,
    name: "Can change inventory",
    content_type_id: 64,
    codename: "change_inventory",
  },
  {
    id: 255,
    name: "Can delete inventory",
    content_type_id: 64,
    codename: "delete_inventory",
  },
  {
    id: 256,
    name: "Can view inventory",
    content_type_id: 64,
    codename: "view_inventory",
  },
  {
    id: 265,
    name: "Can add item",
    content_type_id: 67,
    codename: "add_item",
  },
  {
    id: 266,
    name: "Can change item",
    content_type_id: 67,
    codename: "change_item",
  },
  {
    id: 267,
    name: "Can delete item",
    content_type_id: 67,
    codename: "delete_item",
  },
  {
    id: 268,
    name: "Can view item",
    content_type_id: 67,
    codename: "view_item",
  },
  {
    id: 261,
    name: "Can add order",
    content_type_id: 66,
    codename: "add_order",
  },
  {
    id: 262,
    name: "Can change order",
    content_type_id: 66,
    codename: "change_order",
  },
  {
    id: 263,
    name: "Can delete order",
    content_type_id: 66,
    codename: "delete_order",
  },
  {
    id: 264,
    name: "Can view order",
    content_type_id: 66,
    codename: "view_order",
  },
  {
    id: 249,
    name: "Can add product",
    content_type_id: 63,
    codename: "add_product",
  },
  {
    id: 250,
    name: "Can change product",
    content_type_id: 63,
    codename: "change_product",
  },
  {
    id: 251,
    name: "Can delete product",
    content_type_id: 63,
    codename: "delete_product",
  },
  {
    id: 252,
    name: "Can view product",
    content_type_id: 63,
    codename: "view_product",
  },
  {
    id: 245,
    name: "Can add product category",
    content_type_id: 62,
    codename: "add_productcategory",
  },
  {
    id: 246,
    name: "Can change product category",
    content_type_id: 62,
    codename: "change_productcategory",
  },
  {
    id: 247,
    name: "Can delete product category",
    content_type_id: 62,
    codename: "delete_productcategory",
  },
  {
    id: 248,
    name: "Can view product category",
    content_type_id: 62,
    codename: "view_productcategory",
  },
  {
    id: 257,
    name: "Can add size",
    content_type_id: 65,
    codename: "add_size",
  },
  {
    id: 258,
    name: "Can change size",
    content_type_id: 65,
    codename: "change_size",
  },
  {
    id: 259,
    name: "Can delete size",
    content_type_id: 65,
    codename: "delete_size",
  },
  {
    id: 260,
    name: "Can view size",
    content_type_id: 65,
    codename: "view_size",
  },
  {
    id: 189,
    name: "Can add levels percentage",
    content_type_id: 48,
    codename: "add_levelspercentage",
  },
  {
    id: 190,
    name: "Can change levels percentage",
    content_type_id: 48,
    codename: "change_levelspercentage",
  },
  {
    id: 191,
    name: "Can delete levels percentage",
    content_type_id: 48,
    codename: "delete_levelspercentage",
  },
  {
    id: 192,
    name: "Can view levels percentage",
    content_type_id: 48,
    codename: "view_levelspercentage",
  },
  {
    id: 197,
    name: "Can add Referral",
    content_type_id: 50,
    codename: "add_referral",
  },
  {
    id: 198,
    name: "Can change Referral",
    content_type_id: 50,
    codename: "change_referral",
  },
  {
    id: 199,
    name: "Can delete Referral",
    content_type_id: 50,
    codename: "delete_referral",
  },
  {
    id: 200,
    name: "Can view Referral",
    content_type_id: 50,
    codename: "view_referral",
  },
  {
    id: 193,
    name: "Can add token history",
    content_type_id: 49,
    codename: "add_tokenhistory",
  },
  {
    id: 194,
    name: "Can change token history",
    content_type_id: 49,
    codename: "change_tokenhistory",
  },
  {
    id: 195,
    name: "Can delete token history",
    content_type_id: 49,
    codename: "delete_tokenhistory",
  },
  {
    id: 196,
    name: "Can view token history",
    content_type_id: 49,
    codename: "view_tokenhistory",
  },
  {
    id: 185,
    name: "Can add device registration",
    content_type_id: 47,
    codename: "add_deviceregistration",
  },
  {
    id: 186,
    name: "Can change device registration",
    content_type_id: 47,
    codename: "change_deviceregistration",
  },
  {
    id: 187,
    name: "Can delete device registration",
    content_type_id: 47,
    codename: "delete_deviceregistration",
  },
  {
    id: 188,
    name: "Can view device registration",
    content_type_id: 47,
    codename: "view_deviceregistration",
  },
  {
    id: 181,
    name: "Can add notification",
    content_type_id: 46,
    codename: "add_notification",
  },
  {
    id: 182,
    name: "Can change notification",
    content_type_id: 46,
    codename: "change_notification",
  },
  {
    id: 183,
    name: "Can delete notification",
    content_type_id: 46,
    codename: "delete_notification",
  },
  {
    id: 184,
    name: "Can view notification",
    content_type_id: 46,
    codename: "view_notification",
  },
  {
    id: 277,
    name: "Can add booking_withdraw",
    content_type_id: 70,
    codename: "add_booking_withdraw",
  },
  {
    id: 278,
    name: "Can change booking_withdraw",
    content_type_id: 70,
    codename: "change_booking_withdraw",
  },
  {
    id: 279,
    name: "Can delete booking_withdraw",
    content_type_id: 70,
    codename: "delete_booking_withdraw",
  },
  {
    id: 280,
    name: "Can view booking_withdraw",
    content_type_id: 70,
    codename: "view_booking_withdraw",
  },
  {
    id: 137,
    name: "Can add create wallet",
    content_type_id: 35,
    codename: "add_createwallet",
  },
  {
    id: 138,
    name: "Can change create wallet",
    content_type_id: 35,
    codename: "change_createwallet",
  },
  {
    id: 139,
    name: "Can delete create wallet",
    content_type_id: 35,
    codename: "delete_createwallet",
  },
  {
    id: 140,
    name: "Can view create wallet",
    content_type_id: 35,
    codename: "view_createwallet",
  },
  {
    id: 177,
    name: "Can add customer card info",
    content_type_id: 45,
    codename: "add_customercardinfo",
  },
  {
    id: 178,
    name: "Can change customer card info",
    content_type_id: 45,
    codename: "change_customercardinfo",
  },
  {
    id: 179,
    name: "Can delete customer card info",
    content_type_id: 45,
    codename: "delete_customercardinfo",
  },
  {
    id: 180,
    name: "Can view customer card info",
    content_type_id: 45,
    codename: "view_customercardinfo",
  },
  {
    id: 173,
    name: "Can add mln token panding history",
    content_type_id: 44,
    codename: "add_mlntokenpandinghistory",
  },
  {
    id: 174,
    name: "Can change mln token panding history",
    content_type_id: 44,
    codename: "change_mlntokenpandinghistory",
  },
  {
    id: 175,
    name: "Can delete mln token panding history",
    content_type_id: 44,
    codename: "delete_mlntokenpandinghistory",
  },
  {
    id: 176,
    name: "Can view mln token panding history",
    content_type_id: 44,
    codename: "view_mlntokenpandinghistory",
  },
  {
    id: 169,
    name: "Can add mln tokens earn",
    content_type_id: 43,
    codename: "add_mlntokensearn",
  },
  {
    id: 170,
    name: "Can change mln tokens earn",
    content_type_id: 43,
    codename: "change_mlntokensearn",
  },
  {
    id: 171,
    name: "Can delete mln tokens earn",
    content_type_id: 43,
    codename: "delete_mlntokensearn",
  },
  {
    id: 172,
    name: "Can view mln tokens earn",
    content_type_id: 43,
    codename: "view_mlntokensearn",
  },
  {
    id: 241,
    name: "Can add paid out mnr",
    content_type_id: 61,
    codename: "add_paidoutmnr",
  },
  {
    id: 242,
    name: "Can change paid out mnr",
    content_type_id: 61,
    codename: "change_paidoutmnr",
  },
  {
    id: 243,
    name: "Can delete paid out mnr",
    content_type_id: 61,
    codename: "delete_paidoutmnr",
  },
  {
    id: 244,
    name: "Can view paid out mnr",
    content_type_id: 61,
    codename: "view_paidoutmnr",
  },
  {
    id: 165,
    name: "Can add refund booking",
    content_type_id: 42,
    codename: "add_refundbooking",
  },
  {
    id: 166,
    name: "Can change refund booking",
    content_type_id: 42,
    codename: "change_refundbooking",
  },
  {
    id: 167,
    name: "Can delete refund booking",
    content_type_id: 42,
    codename: "delete_refundbooking",
  },
  {
    id: 168,
    name: "Can view refund booking",
    content_type_id: 42,
    codename: "view_refundbooking",
  },
  {
    id: 161,
    name: "Can add stripe booking",
    content_type_id: 41,
    codename: "add_stripebooking",
  },
  {
    id: 162,
    name: "Can change stripe booking",
    content_type_id: 41,
    codename: "change_stripebooking",
  },
  {
    id: 163,
    name: "Can delete stripe booking",
    content_type_id: 41,
    codename: "delete_stripebooking",
  },
  {
    id: 164,
    name: "Can view stripe booking",
    content_type_id: 41,
    codename: "view_stripebooking",
  },
  {
    id: 157,
    name: "Can add stripe connect account",
    content_type_id: 40,
    codename: "add_stripeconnectaccount",
  },
  {
    id: 158,
    name: "Can change stripe connect account",
    content_type_id: 40,
    codename: "change_stripeconnectaccount",
  },
  {
    id: 159,
    name: "Can delete stripe connect account",
    content_type_id: 40,
    codename: "delete_stripeconnectaccount",
  },
  {
    id: 160,
    name: "Can view stripe connect account",
    content_type_id: 40,
    codename: "view_stripeconnectaccount",
  },
  {
    id: 153,
    name: "Can add stripe customer",
    content_type_id: 39,
    codename: "add_stripecustomer",
  },
  {
    id: 154,
    name: "Can change stripe customer",
    content_type_id: 39,
    codename: "change_stripecustomer",
  },
  {
    id: 155,
    name: "Can delete stripe customer",
    content_type_id: 39,
    codename: "delete_stripecustomer",
  },
  {
    id: 156,
    name: "Can view stripe customer",
    content_type_id: 39,
    codename: "view_stripecustomer",
  },
  {
    id: 149,
    name: "Can add token rate",
    content_type_id: 38,
    codename: "add_tokenrate",
  },
  {
    id: 150,
    name: "Can change token rate",
    content_type_id: 38,
    codename: "change_tokenrate",
  },
  {
    id: 151,
    name: "Can delete token rate",
    content_type_id: 38,
    codename: "delete_tokenrate",
  },
  {
    id: 152,
    name: "Can view token rate",
    content_type_id: 38,
    codename: "view_tokenrate",
  },
  {
    id: 237,
    name: "Can add top up",
    content_type_id: 60,
    codename: "add_topup",
  },
  {
    id: 238,
    name: "Can change top up",
    content_type_id: 60,
    codename: "change_topup",
  },
  {
    id: 239,
    name: "Can delete top up",
    content_type_id: 60,
    codename: "delete_topup",
  },
  {
    id: 240,
    name: "Can view top up",
    content_type_id: 60,
    codename: "view_topup",
  },
  {
    id: 145,
    name: "Can add user bnb",
    content_type_id: 37,
    codename: "add_userbnb",
  },
  {
    id: 146,
    name: "Can change user bnb",
    content_type_id: 37,
    codename: "change_userbnb",
  },
  {
    id: 147,
    name: "Can delete user bnb",
    content_type_id: 37,
    codename: "delete_userbnb",
  },
  {
    id: 148,
    name: "Can view user bnb",
    content_type_id: 37,
    codename: "view_userbnb",
  },
  {
    id: 141,
    name: "Can add wallet history",
    content_type_id: 36,
    codename: "add_wallethistory",
  },
  {
    id: 142,
    name: "Can change wallet history",
    content_type_id: 36,
    codename: "change_wallethistory",
  },
  {
    id: 143,
    name: "Can delete wallet history",
    content_type_id: 36,
    codename: "delete_wallethistory",
  },
  {
    id: 144,
    name: "Can view wallet history",
    content_type_id: 36,
    codename: "view_wallethistory",
  },
  {
    id: 209,
    name: "Can add about content",
    content_type_id: 53,
    codename: "add_aboutcontent",
  },
  {
    id: 210,
    name: "Can change about content",
    content_type_id: 53,
    codename: "change_aboutcontent",
  },
  {
    id: 211,
    name: "Can delete about content",
    content_type_id: 53,
    codename: "delete_aboutcontent",
  },
  {
    id: 212,
    name: "Can view about content",
    content_type_id: 53,
    codename: "view_aboutcontent",
  },
  {
    id: 205,
    name: "Can add privacy policy",
    content_type_id: 52,
    codename: "add_privacypolicy",
  },
  {
    id: 206,
    name: "Can change privacy policy",
    content_type_id: 52,
    codename: "change_privacypolicy",
  },
  {
    id: 207,
    name: "Can delete privacy policy",
    content_type_id: 52,
    codename: "delete_privacypolicy",
  },
  {
    id: 208,
    name: "Can view privacy policy",
    content_type_id: 52,
    codename: "view_privacypolicy",
  },
  {
    id: 201,
    name: "Can add terms and condition",
    content_type_id: 51,
    codename: "add_termsandcondition",
  },
  {
    id: 202,
    name: "Can change terms and condition",
    content_type_id: 51,
    codename: "change_termsandcondition",
  },
  {
    id: 203,
    name: "Can delete terms and condition",
    content_type_id: 51,
    codename: "delete_termsandcondition",
  },
  {
    id: 204,
    name: "Can view terms and condition",
    content_type_id: 51,
    codename: "view_termsandcondition",
  },
  {
    id: 113,
    name: "Can add sp item images",
    content_type_id: 29,
    codename: "add_spitemimages",
  },
  {
    id: 114,
    name: "Can change sp item images",
    content_type_id: 29,
    codename: "change_spitemimages",
  },
  {
    id: 115,
    name: "Can delete sp item images",
    content_type_id: 29,
    codename: "delete_spitemimages",
  },
  {
    id: 116,
    name: "Can view sp item images",
    content_type_id: 29,
    codename: "view_spitemimages",
  },
  {
    id: 109,
    name: "Can add sp items",
    content_type_id: 28,
    codename: "add_spitems",
  },
  {
    id: 110,
    name: "Can change sp items",
    content_type_id: 28,
    codename: "change_spitems",
  },
  {
    id: 111,
    name: "Can delete sp items",
    content_type_id: 28,
    codename: "delete_spitems",
  },
  {
    id: 112,
    name: "Can view sp items",
    content_type_id: 28,
    codename: "view_spitems",
  },
  {
    id: 21,
    name: "Can add session",
    content_type_id: 6,
    codename: "add_session",
  },
  {
    id: 22,
    name: "Can change session",
    content_type_id: 6,
    codename: "change_session",
  },
  {
    id: 23,
    name: "Can delete session",
    content_type_id: 6,
    codename: "delete_session",
  },
  {
    id: 24,
    name: "Can view session",
    content_type_id: 6,
    codename: "view_session",
  },
  {
    id: 125,
    name: "Can add tickets",
    content_type_id: 32,
    codename: "add_tickets",
  },
  {
    id: 126,
    name: "Can change tickets",
    content_type_id: 32,
    codename: "change_tickets",
  },
  {
    id: 127,
    name: "Can delete tickets",
    content_type_id: 32,
    codename: "delete_tickets",
  },
  {
    id: 128,
    name: "Can view tickets",
    content_type_id: 32,
    codename: "view_tickets",
  },
  {
    id: 49,
    name: "Can add blacklisted token",
    content_type_id: 13,
    codename: "add_blacklistedtoken",
  },
  {
    id: 50,
    name: "Can change blacklisted token",
    content_type_id: 13,
    codename: "change_blacklistedtoken",
  },
  {
    id: 51,
    name: "Can delete blacklisted token",
    content_type_id: 13,
    codename: "delete_blacklistedtoken",
  },
  {
    id: 52,
    name: "Can view blacklisted token",
    content_type_id: 13,
    codename: "view_blacklistedtoken",
  },
  {
    id: 53,
    name: "Can add outstanding token",
    content_type_id: 14,
    codename: "add_outstandingtoken",
  },
  {
    id: 54,
    name: "Can change outstanding token",
    content_type_id: 14,
    codename: "change_outstandingtoken",
  },
  {
    id: 55,
    name: "Can delete outstanding token",
    content_type_id: 14,
    codename: "delete_outstandingtoken",
  },
  {
    id: 56,
    name: "Can view outstanding token",
    content_type_id: 14,
    codename: "view_outstandingtoken",
  },
  {
    id: 121,
    name: "Can add twilio chat",
    content_type_id: 31,
    codename: "add_twiliochat",
  },
  {
    id: 122,
    name: "Can change twilio chat",
    content_type_id: 31,
    codename: "change_twiliochat",
  },
  {
    id: 123,
    name: "Can delete twilio chat",
    content_type_id: 31,
    codename: "delete_twiliochat",
  },
  {
    id: 124,
    name: "Can view twilio chat",
    content_type_id: 31,
    codename: "view_twiliochat",
  },
  {
    id: 229,
    name: "Can add twilio users",
    content_type_id: 58,
    codename: "add_twiliousers",
  },
  {
    id: 230,
    name: "Can change twilio users",
    content_type_id: 58,
    codename: "change_twiliousers",
  },
  {
    id: 231,
    name: "Can delete twilio users",
    content_type_id: 58,
    codename: "delete_twiliousers",
  },
  {
    id: 232,
    name: "Can view twilio users",
    content_type_id: 58,
    codename: "view_twiliousers",
  },
  {
    id: 25,
    name: "Can add permissions",
    content_type_id: 7,
    codename: "add_permissions",
  },
  {
    id: 26,
    name: "Can change permissions",
    content_type_id: 7,
    codename: "change_permissions",
  },
  {
    id: 27,
    name: "Can delete permissions",
    content_type_id: 7,
    codename: "delete_permissions",
  },
  {
    id: 28,
    name: "Can view permissions",
    content_type_id: 7,
    codename: "view_permissions",
  },
  {
    id: 29,
    name: "Can add role",
    content_type_id: 8,
    codename: "add_role",
  },
  {
    id: 30,
    name: "Can change role",
    content_type_id: 8,
    codename: "change_role",
  },
  {
    id: 31,
    name: "Can delete role",
    content_type_id: 8,
    codename: "delete_role",
  },
  {
    id: 32,
    name: "Can view role",
    content_type_id: 8,
    codename: "view_role",
  },
  {
    id: 37,
    name: "Can add user addresses",
    content_type_id: 10,
    codename: "add_useraddresses",
  },
  {
    id: 38,
    name: "Can change user addresses",
    content_type_id: 10,
    codename: "change_useraddresses",
  },
  {
    id: 39,
    name: "Can delete user addresses",
    content_type_id: 10,
    codename: "delete_useraddresses",
  },
  {
    id: 40,
    name: "Can view user addresses",
    content_type_id: 10,
    codename: "view_useraddresses",
  },
  {
    id: 33,
    name: "Can add user profile",
    content_type_id: 9,
    codename: "add_userprofile",
  },
  {
    id: 34,
    name: "Can change user profile",
    content_type_id: 9,
    codename: "change_userprofile",
  },
  {
    id: 35,
    name: "Can delete user profile",
    content_type_id: 9,
    codename: "delete_userprofile",
  },
  {
    id: 36,
    name: "Can view user profile",
    content_type_id: 9,
    codename: "view_userprofile",
  },
];
